package com.ryo.boot2.dao;

import com.ryo.boot2.model.Girls;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface GirlsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls
     *
     * @mbggenerated
     */
    int insert(Girls record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls
     *
     * @mbggenerated
     */
    Girls selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls
     *
     * @mbggenerated
     */
    List<Girls> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table girls
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Girls record);
}