server:
  port: 8091
spring:
  data:
    mongodb:
      uri:  mongodb://mongoip:27017/test
  datasource:
     url: jdbc:mysql://mysqlip:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true



