package com.ryo.boot2.model;

public class Girls {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girls.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girls.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girls.cupsize
     *
     * @mbggenerated
     */
    private String cupsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column girls.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girls.id
     *
     * @return the value of girls.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girls.id
     *
     * @param id the value for girls.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girls.name
     *
     * @return the value of girls.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girls.name
     *
     * @param name the value for girls.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girls.cupsize
     *
     * @return the value of girls.cupsize
     *
     * @mbggenerated
     */
    public String getCupsize() {
        return cupsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girls.cupsize
     *
     * @param cupsize the value for girls.cupsize
     *
     * @mbggenerated
     */
    public void setCupsize(String cupsize) {
        this.cupsize = cupsize == null ? null : cupsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column girls.age
     *
     * @return the value of girls.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column girls.age
     *
     * @param age the value for girls.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}